################## LOGIN / USER ####################

### REGISTER/CREATE USER
POST http://localhost:5001/api/v1/user/register
Content-Type: application/json

{
  "firstName": "Frank",
  "lastName": "Lampard",
  "email": "fl@o.com",
  "password": "vangunneR@45",
  "userName": "fl8"
}

### CLIENT LOGIN
POST http://localhost:5001/api/v1/auth/login
Content-Type: application/json

{
  "email": "jm@m.com",
  "password": "vangunneR@45"
}


### LOGOUT
PUT http://localhost:5001/api/v1/auth/logout
Content-Type: application/json

{
  "accessJwt" :"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImptQG0uY29tIiwiX2lkIjoiNjIxNmZhZmU2M2Q4YzI5ODNlNjVmZTY3IiwiaWF0IjoxNjQ1NzA1MTk4LCJleHAiOjE2NDc0MzMxOTh9.PwAba-3F2IsX2QoYZTUS0aTigqOAAceQ7M2StmOmjUA",
  "refreshJwt": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImptQG0uY29tIiwiaWF0IjoxNjQ1NzA1MTk4LCJleHAiOjE2NDgyOTcxOTh9.kti_0E_jKJHgNsVR97JkXw0qzz5EKxkZ29JcTg5j0gk"
}

### OTP REQUEST
POST http://localhost:5001/api/v1/auth/otp
Content-Type: application/json

{
  "email" : "jm@m.com"
}

### UPDATE PASSWORD
PATCH http://localhost:5001/api/v1/auth/password
Content-Type: application/json

{
  "pin": 67720,
  "email": "jm@m.com",
  "password" : "aspirinE@49"
}


### GET ALL CLIENTS
GET http://localhost:5001/api/v1/user/all


################## PRODUCTS ####################

### GET ALL PRODUCTS
GET http://localhost:5001/api/v1/product?category=Electronics

### GET PRODUCT BY ID
GET http://localhost:5001/api/v1/product/621ee3d7f2963f611f471271


################## CATEGORIES ####################

GET http://localHost:5001/api/v1/category

################## ORDERS ####################

// GET ALL ORDERS
GET http://localHost:5001/api/v1/order


// GET ORDER BY CLIENT ID
###
GET http://localHost:5001/api/v1/order/single
Content-Type: application/json

{
  "_id": "622ff2705966a728d4309ac1"
}


// GET MONTHLY INCOME
###
GET http://localHost:5001/api/v1/order/income


// SAVE ORDER
###
POST http://localHost:5001/api/v1/order
Content-Type: application/json

{
  "clientId" : "6246eaa891314747f2fefad9",
  "products" : [
    {
      "productId": "122356",
      "quantity": 20
    }  
  ],
   "amount": 120,
   "address": "10 queen highway",
   "status":"success"
}

